version: '3.8'

services:
  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data: