// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: common/proto/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NsqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Message:
	//
	//	*NsqMessage_NewOrder
	//	*NsqMessage_PaymentSuccessfull
	Message isNsqMessage_Message `protobuf_oneof:"message"`
}

func (x *NsqMessage) Reset() {
	*x = NsqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NsqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsqMessage) ProtoMessage() {}

func (x *NsqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsqMessage.ProtoReflect.Descriptor instead.
func (*NsqMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *NsqMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *NsqMessage) GetMessage() isNsqMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *NsqMessage) GetNewOrder() *NewOrder {
	if x, ok := x.GetMessage().(*NsqMessage_NewOrder); ok {
		return x.NewOrder
	}
	return nil
}

func (x *NsqMessage) GetPaymentSuccessfull() *PaymentSuccessfull {
	if x, ok := x.GetMessage().(*NsqMessage_PaymentSuccessfull); ok {
		return x.PaymentSuccessfull
	}
	return nil
}

type isNsqMessage_Message interface {
	isNsqMessage_Message()
}

type NsqMessage_NewOrder struct {
	NewOrder *NewOrder `protobuf:"bytes,2,opt,name=new_order,json=newOrder,proto3,oneof"`
}

type NsqMessage_PaymentSuccessfull struct {
	PaymentSuccessfull *PaymentSuccessfull `protobuf:"bytes,3,opt,name=payment_successfull,json=paymentSuccessfull,proto3,oneof"`
}

func (*NsqMessage_NewOrder) isNsqMessage_Message() {}

func (*NsqMessage_PaymentSuccessfull) isNsqMessage_Message() {}

type NewOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NewOrder) Reset() {
	*x = NewOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrder) ProtoMessage() {}

func (x *NewOrder) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrder.ProtoReflect.Descriptor instead.
func (*NewOrder) Descriptor() ([]byte, []int) {
	return file_common_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *NewOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PaymentSuccessfull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *PaymentSuccessfull) Reset() {
	*x = PaymentSuccessfull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSuccessfull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessfull) ProtoMessage() {}

func (x *PaymentSuccessfull) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessfull.ProtoReflect.Descriptor instead.
func (*PaymentSuccessfull) Descriptor() ([]byte, []int) {
	return file_common_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentSuccessfull) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_common_proto_messages_proto protoreflect.FileDescriptor

var file_common_proto_messages_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xaf, 0x01, 0x0a, 0x0a, 0x4e, 0x73, 0x71, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x6e, 0x65,
	0x77, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x4f, 0x0a,
	0x13, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x12, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x6c, 0x42, 0x09,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x77,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x12, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x42, 0x1a, 0x5a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_messages_proto_rawDescOnce sync.Once
	file_common_proto_messages_proto_rawDescData = file_common_proto_messages_proto_rawDesc
)

func file_common_proto_messages_proto_rawDescGZIP() []byte {
	file_common_proto_messages_proto_rawDescOnce.Do(func() {
		file_common_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_messages_proto_rawDescData)
	})
	return file_common_proto_messages_proto_rawDescData
}

var file_common_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_messages_proto_goTypes = []interface{}{
	(*NsqMessage)(nil),         // 0: messages.NsqMessage
	(*NewOrder)(nil),           // 1: messages.NewOrder
	(*PaymentSuccessfull)(nil), // 2: messages.PaymentSuccessfull
}
var file_common_proto_messages_proto_depIdxs = []int32{
	1, // 0: messages.NsqMessage.new_order:type_name -> messages.NewOrder
	2, // 1: messages.NsqMessage.payment_successfull:type_name -> messages.PaymentSuccessfull
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_messages_proto_init() }
func file_common_proto_messages_proto_init() {
	if File_common_proto_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NsqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSuccessfull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_proto_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NsqMessage_NewOrder)(nil),
		(*NsqMessage_PaymentSuccessfull)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_messages_proto_goTypes,
		DependencyIndexes: file_common_proto_messages_proto_depIdxs,
		MessageInfos:      file_common_proto_messages_proto_msgTypes,
	}.Build()
	File_common_proto_messages_proto = out.File
	file_common_proto_messages_proto_rawDesc = nil
	file_common_proto_messages_proto_goTypes = nil
	file_common_proto_messages_proto_depIdxs = nil
}
